spring:
  application:
    name: institutions
server:
  port: 8081
app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5431/institutions
      username: institutions_service
      password: institutions_service
      pool-size: 1
    server:
      error:
        include-binding-errors: always
        include-message: always