spring:
  application:
    name: education
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
    exchange: appExchange
    queues:
      courses:
        request: coursesRequestQueue
    keys:
      courses:
        request: coursesRequestKey

server:
  port: 8082
  tomcat:
    max-swallow-size: 50MB

app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5433/education
      username: education_service
      password: education_service
      pool-size: 1
    server:
      error:
        include-binding-errors: always
        include-message: always

aws:
  bucket:
    name: symfoititis
  access:
    key: 
  secret:
    key: 
