spring:
  application:
    name: tutoring

  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
    exchange: appExchange
    queues:
      chatRooms: chatRoomsQueue
      courses:
        request: coursesRequestQueue
        reply: coursesReplyQueue
    keys:
      chatRooms: chatRoomsKey
      courses:
        request: coursesRequestKey
        reply: coursesReplyKey

server:
  port: 8083

redis:
  host: localhost
  port: 6379

app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5434/tutoring
      username: tutoring_service
      password: tutoring_service
      pool-size: 1
    server:
      error:
        include-binding-errors: always
        include-message: always

auth:
  student:
    client_id: student-service-account
    client_secret: yoL0mTsgyQ2VNLkkyxYXe0tCOTn2PZIy
    token:
      base_url: http://localhost:8080/auth/realms/student
    admin:
      base_url: http://localhost:8080/auth/admin/realms/student
  teacher:
    client_id: teacher-service-account
    client_secret: 
    token:
      base_url: http://localhost:8080/auth/realms/teacher
    admin:
      base_url: http://localhost:8080/auth/admin/realms/teacher

email:
  sendgrid:
    key: 
