spring:
  application:
    name: chat
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
    exchange: appExchange
    queues:
      chatRooms: chatRoomsQueue
    keys:
      chatRooms: chatRoomsKey

server:
  port: 8084
  tomcat:
    max-swallow-size: 50MB

app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5436/chat
      username: chat_service
      password: chat_service
      pool-size: 1
    server:
      error:
        include-binding-errors: always
        include-message: always

aws:
  bucket:
    name: symfoititis
  access:
    key: 
  secret:
    key: 
