#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="$POSTGRES_DB" <<-EOSQL
        CREATE USER ${SERVICE_USER} WITH PASSWORD '${SERVICE_PASSWORD}';
        GRANT SELECT, INSERT, UPDATE ON TABLE availability_slots TO ${SERVICE_USER};
        GRANT SELECT, INSERT, UPDATE ON TABLE availability_events TO ${SERVICE_USER};
        GRANT SELECT, INSERT, UPDATE ON TABLE bookings TO ${SERVICE_USER};
        GRANT SELECT, INSERT, UPDATE ON TABLE booking_events TO ${SERVICE_USER};
        GRANT SELECT, INSERT, UPDATE ON TABLE purchase_products TO ${SERVICE_USER};
        GRANT SELECT, INSERT, UPDATE ON TABLE student_balance TO ${SERVICE_USER};
EOSQL
